server:
  port: 8081
#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp?serverTimezone=UTC
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false


##mybatis
#mybatis:
#  type-aliases-package: com.mp.pojo
#  mapper-locations: classpath:mappers/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#日志记录
logging:
  level:
    com:
     mp:
      mapper: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.mp.pojo




